# Generated by Django 4.0.6 on 2022-07-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_txt', models.CharField(max_length=15)),
                ('en_txt', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_sub_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_txt', models.CharField(max_length=15)),
                ('en_txt', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_level_menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_txt', models.CharField(max_length=15)),
                ('en_txt', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_level_menu.menu')),
            ],
        ),
    ]
