# Generated by Django 4.0.6 on 2022-07-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_level_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_sub_menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_level_menu.sub_menu'),
        ),
    ]
